# logging options
save_dir: /home/ubuntu/logs/idkidc
project: MSI_transformer
name: debug

# task definition
data_config: /home/ubuntu/projects/idkidc/data_config.yaml
task: binary
target: isMSIH
num_classes: 1
cohorts: ["TCGA"]
ext_cohorts: []
clini_info: {}
seed: null
label_dict:
  Not mut.: 0
  Mutat.: 1
  nonMSIH: 0
  MSIH: 1
  WT: 0
  MUT: 1
  wt: 0
  MT: 1
  # clinical information
  left: 1
  right: 0
  female: 1
  male: 0
  # CRC staging
  Stage I: 0
  Stage II: 1
  Stage III: 2
  Stage IV: 3
  # dermAI / HistoGPT project
  Aktinische Keratose: 0
  Basalzellkarzinom: 1
  Benign Neoplasm: 2
  Spinozelluläres Karzinom: 3

# model options
model: AttentionMIL
model_config:  # null
  heads: 4
  dim_head: 64
  dim: 256
  mlp_dim: 256
  pos_enc: null
norm: histaugan
feats: ctranspath
input_dim: 768
num_tiles: 8000
pad_tiles: false

# training options
folds: 5
num_epochs: 1
criterion:  BCEWithLogitsLoss # CrossEntropyLoss
optimizer: Adam
lr_scheduler: OneCycleLR
lr_scheduler_config: # null
  max_lr: 1.0e-03
lr: 1.0e-04
wd: 1.0e-02
bs: 1
stop_criterion: loss
val_check_interval: 500
num_samples: null