COHORT_NAME:
  targets:
    - target_label
  clini_table: /path/to/table/with/clinical/annotations.xlsx
  slide_csv: /path/to/csv/file/with/slide/names/per/patient.csv
  feature_dir:
    normalization/augmentation:  # in ['raw', 'histaugan', 'macenko']
      ctranspath: /path/to/folder/with/features  # in ['ctranspath', 'retccl']
