"""
config file for data paths. common normalization methods are macenko or raw 
"""

<cohort_name>:
  clini_table: /path/to/excel/table.xlsx
  slide_csv: /path/to/slide/table.csv
  feature_dir:
    <normalization_method_1>:
      <feature_extractor_1>: /path/to/feature_directory
      <feature_extractor_2>: /path/to/feature_directory
    <normalization_method_2>:
      <feature_extractor_1>: /path/to/feature_directory
