Rainbow:
  targets:
    - braf
    - isMSIH
    - kras
    - nras
    - pik3ca
  clini_table: /mnt/Mars_03_CRC_WSIs/Jan/desktop/RAINBOW_CRC/RAINBOW-CRCREPROCESS-MM-DX_CLINI.xlsx
  slide_csv: /mnt/Mars_03_CRC_WSIs/Jan/desktop/RAINBOW_CRC/RAINBOW-CRCREPROCESS-MM-DX_SLIDE.csv
  feature_dir: /home/janniehues/Documents/CRC_Rainbow/features/Xiyue-Wang/
Quasar:
  targets:
    - BRAF
    - isMSIH
    - KRAS
    - NRAS
  clini_table: /home/janniehues/Documents/CRC_Quasar/QUASAR_CLINI_DATA/QUASAR-CRC-DX_CLINI.xlsx
  slide_csv: /home/janniehues/Documents/CRC_Quasar/QUASAR_CLINI_DATA/QUASAR-CRC-DX_SLIDE.csv
  feature_dir: /home/janniehues/Documents/CRC_Quasar/features/Xiyue-Wang/
