CHINA:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/CHINA-CRC-DX_clini.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/CHINA-CRC-DX_slide.csv
  feature_dir:
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/CHINA-CRC-DX/features/histaugan_ctranspath
    macenko:
      ctranspath: /lustre/groups/peng/datasets/histology_data/CHINA-CRC-DX/features/histaugan_macenko_ctranspath
    raw:
      ctranspath: /lustre/groups/peng/datasets/histology_data/CHINA-CRC-DX/features/raw_ctranspath

CPTAC:
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/coad_cptac_2019_clinical_data.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/coad_cptac_2019_slide.csv
  # clini_table: /home/ubuntu/data/CPTAC-COAD/coad_cptac_2019_clinical_data.xlsx
  # slide_csv: /home/ubuntu/data/CPTAC-COAD/coad_cptac_2019_slide.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Macenko/RetCCL/
      ctranspath: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Macenko/CTransPath/
      # ctranspath: /home/ubuntu/data/CPTAC-COAD/features/CPTAC_Macenko_CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Raw/RetCCL/
      ctranspath: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Raw/CPTAC_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Raw/CPTAC_HistAuGAN_CTransPath/

DACHS:
  targets:
    - braf
    - isMSIH
    - kras
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/DACHS-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/DACHS-CRC-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/DACHS/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/DACHS/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/DACHS/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/DACHS/features/Raw/Dachs_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/DACHS/features/Raw/Dachs_HistAuGAN_CTransPath/

DUSSEL:
  targets:
    - BRAF
    - isMSIH
    - KRAS
    - NRAS
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/DUSSEL-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/DUSSEL-CRC-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/DUSSEL/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/DUSSEL/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/DUSSEL/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/DUSSEL/features/Raw/DUSSEL_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/DUSSEL/features/Raw/DUSSEL_HistAuGAN_CTransPath/

Epi700:
  targets:
    - braf
    - isMSIH
    - kras
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/BELFAST-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/BELFAST-CRC-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/BELFAST/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/BELFAST/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/BELFAST/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/BELFAST/features/Raw/BELFAST_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/BELFAST/features/Raw/BELFAST_HistAuGAN_CTransPath/

ERLANGEN:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/ERLANGEN-CRC-DX_clini.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/ERLANGEN-CRC-DX_slide.csv
  feature_dir:
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/ERLANGEN/features/histaugan_ctranspath
    raw:
      ctranspath: /lustre/groups/peng/datasets/histology_data/ERLANGEN/features/raw_ctranspath

FOXTROT:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/FOXTROT-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/FOXTROT-CRC-DX_resection_tumor_slide.csv
  feature_dir:
    macenko:
      ctranspath: /lustre/groups/peng/datasets/histology_data/FOXTROT/features/Macenko/FOXTROT-CRC-DX_macenko_ctranspath/
    histaugan: 
      ctranspath: /lustre/groups/peng/datasets/histology_data/FOXTROT/features/FOXTROT-CRC-DX-features-histaugan/
    raw: 
      ctranspath: /lustre/groups/peng/datasets/histology_data/FOXTROT/features/FOXTROT-CRC-DX-features-histaugan/

MAINZ:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/MAINZ-BIOPSIES-CRC-DX_clini.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/MAINZ-BIOPSIES-CRC-DX_slide.csv
  feature_dir:
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/MAINZ-BIOPSIES-CRC-DX/features/CTransPath_HistAuGAN/
    raw:
      ctranspath: /lustre/groups/peng/datasets/histology_data/MAINZ-BIOPSIES-CRC-DX/features/CTransPath_HistAuGAN/

MCO:
  targets:
    - isMSIH
    - BRAF
    - KRAS
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/MCO-CRC-DX_clini_full_braf_kras.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/MCO-CRC-DX_slide.csv
  feature_dir:
    macenko:
      ctranspath: /lustre/groups/peng/datasets/histology_data/MCO-CRC-DX/features/Macenko/CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/MCO-CRC-DX/features/ctranspath_histaugan/
    raw:
      ctranspath: /lustre/groups/peng/datasets/histology_data/MCO-CRC-DX/features/ctranspath_histaugan/

MECC:
  targets:
    - BRAF
    - isMSIH
    - KRAS
    - NRAS
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/MECC-CRCBATCH1234-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/MECC-CRCBATCH1234-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/MECC/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/MECC/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/MECC/features/Raw/RetCCL/
      ctranspath: /lustre/groups/peng/datasets/histology_data/MECC/features/Raw/MECC_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/MECC/features/Raw/MECC_HistAuGAN_CTransPath/

MUNICH:
  targets:
    - BRAF
    - isMSIH
    - KRAS
    - NRAS
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/MUCBERN-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/MUCBERN-CRC-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/MUNICH/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/MUNICH/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/MUNICH/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/MUNICH/features/Raw/MUNICH_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/MUNICH/features/Raw/MUNICH_HistAuGAN_CTransPath/
    
QUASAR:
  targets:
    - BRAF
    - isMSIH
    - KRAS
    - NRAS
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/QUASAR-CRC-DX_CLINI_cliniinfo.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/QUASAR-CRC-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/QUASAR/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/QUASAR/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/QUASAR/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/QUASAR/features/Raw/Quasar_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/QUASAR/features/Raw/Quasar_HistAuGAN_CTransPath/

RAINBOW:
  targets:
    - braf
    - isMSIH
    - kras
    - nras
    - pik3ca
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/RAINBOW-CRCREPROCESS-MM-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/RAINBOW-CRCREPROCESS-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/RAINBOW/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/RAINBOW/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/RAINBOW/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/RAINBOW/features/Raw/Rainbow_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/RAINBOW/features/Raw/Rainbow_HistAuGAN_CTransPath/

TCGA:
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-CRC-DX_CLINI.xlsx
  # clini_table: /home/ubuntu/data/TCGA-CRC/TCGA-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-CRC-DX_SLIDE.csv
  # slide_csv: /home/ubuntu/data/TCGA-CRC/TCGA-CRC-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/TCGA-CRC/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/TCGA-CRC/features/Macenko/CTransPath/
      # ctranspath: /home/ubuntu/data/TCGA-CRC/features/TCGA_Macenko_CTransPath/
    raw:
      ctranspath: /lustre/groups/peng/datasets/histology_data/TCGA-CRC/features/marugoto_histaugan/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/TCGA-CRC/features/marugoto_histaugan/
    efficient_histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/TCGA-CRC/features/marugoto_efficient_histaugan/

TRANSCOT:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/TRANSCOT-CRC-DX_clini_table.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/TRANSCOT-CRC-DX_SLIDE.csv
  feature_dir:
    macenko:
      ctranspath: /lustre/groups/peng/datasets/histology_data/TRANSCOT/features/Macenko/TRANSCOT-CRC-DX_macenko_ctranspath/
    raw:  # careful: still macenko!
      ctranspath: /lustre/groups/peng/datasets/histology_data/TRANSCOT/features/Macenko/TRANSCOT-CRC-DX_macenko_ctranspath/
    histaugan:  # careful: still macenko!
      ctranspath: /lustre/groups/peng/datasets/histology_data/TRANSCOT/features/Macenko/TRANSCOT-CRC-DX_macenko_ctranspath/

YCR-BCIP-biopsies:
  targets:
    - BRAF
    - isMSIH
    - KRAS
    - NRAS
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/YORKSHIRE-BIOPSIESFULL-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/YORKSHIRE-BIOPSIESFULL-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Raw/Yorkshire_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Raw/Yorkshire_HistAuGAN_CTransPath/

YCR-BCIP-resections:
  targets:
    - BRAF
    - isMSIH
    - KRAS
    - NRAS
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/YORKSHIRE-RESECTIONS-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/YORKSHIRE-RESECTIONS-DX_SLIDE.csv
  feature_dir:
    macenko:
      retccl: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Macenko/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Macenko/CTransPath/
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Raw/Xiyue-Wang/
      ctranspath: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Raw/Yorkshire_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/YORKSHIRE/features/Raw/Yorkshire_HistAuGAN_CTransPath/

# STAD cohorts
BERN-STAD:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/BERN-STAD-Classification-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/BERN-STAD-Classification-DX_SLIDE.csv
  feature_dir:
    macenko: /lustre/groups/peng/datasets/histology_data/BERN-STAD/features/Macenko/RetCCL/

KCCH-STAD:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/KCCH-STAD-DX_Wholeslide_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/KCCH-STAD-DX_Wholeslide_SLIDE.csv
  feature_dir:
    macenko: /lustre/groups/peng/datasets/histology_data/KCCH-STAD/features/Macenko/RetCCL/

KIEL-STAD:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/KIEL-STAD-DX_GC_Subtype_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/KIEL-STAD-DX-WSI_pythontiles_SLIDE.csv
  feature_dir:
    macenko: /lustre/groups/peng/datasets/histology_data/KIEL-STAD/features/Macenko/RetCCL/

LEEDS-STAD:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/LEEDS-STAD-DX_GC_Subtype_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/LEEDS-STAD-DX-WSI_pythontiles_SLIDE.csv
  feature_dir:
    macenko: /lustre/groups/peng/datasets/histology_data/LEEDS-STAD/features/Macenko/RetCCL/

TCGA-STAD:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-STAD-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-STAD-Classification-DX_SLIDE.csv
  feature_dir:
    macenko: /lustre/groups/peng/datasets/histology_data/TCGA-STAD/features/Macenko/RetCCL/

TUM-STAD:
  targets:
    - isMSIH
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/TUM-STAD-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/TUM-STAD-DX_Wholeslide_SLIDE.csv
  feature_dir:
    macenko: /lustre/groups/peng/datasets/histology_data/TUM-STAD/features/Macenko/RetCCL/
